// Mocks generated by Mockito 5.4.4 from annotations
// in sehatlocker/test/services/batch_processing_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i24;
import 'dart:ui' as _i27;

import 'package:battery_plus/battery_plus.dart' as _i31;
import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter/material.dart' as _i29;
import 'package:flutter/services.dart' as _i28;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i7;
import 'package:hive_flutter/hive_flutter.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:sehatlocker/models/app_settings.dart' as _i4;
import 'package:sehatlocker/models/auth_audit_entry.dart' as _i20;
import 'package:sehatlocker/models/batch_task.dart' as _i10;
import 'package:sehatlocker/models/citation.dart' as _i12;
import 'package:sehatlocker/models/consent_entry.dart' as _i22;
import 'package:sehatlocker/models/conversation_memory.dart' as _i15;
import 'package:sehatlocker/models/doctor_conversation.dart' as _i17;
import 'package:sehatlocker/models/document_extraction.dart' as _i16;
import 'package:sehatlocker/models/export_audit_entry.dart' as _i19;
import 'package:sehatlocker/models/follow_up_item.dart' as _i11;
import 'package:sehatlocker/models/health_record.dart' as _i5;
import 'package:sehatlocker/models/issue_report.dart' as _i21;
import 'package:sehatlocker/models/local_audit_entry.dart' as _i14;
import 'package:sehatlocker/models/recording_audit_entry.dart' as _i18;
import 'package:sehatlocker/services/battery_monitor_service.dart' as _i30;
import 'package:sehatlocker/services/desktop_notification_service.dart' as _i26;
import 'package:sehatlocker/services/local_storage_service.dart' as _i9;
import 'package:sehatlocker/services/memory_monitor_service.dart' as _i8;
import 'package:sehatlocker/services/storage_usage_service.dart' as _i6;
import 'package:sehatlocker/services/vault_service.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSettings_2 extends _i1.SmartFake implements _i4.AppSettings {
  _FakeAppSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHealthRecord_3 extends _i1.SmartFake implements _i5.HealthRecord {
  _FakeHealthRecord_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageUsage_4 extends _i1.SmartFake implements _i6.StorageUsage {
  _FakeStorageUsage_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterLocalNotificationsPlugin_5 extends _i1.SmartFake
    implements _i7.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryStatus_6 extends _i1.SmartFake implements _i8.MemoryStatus {
  _FakeMemoryStatus_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i9.LocalStorageService {
  @override
  _i2.ValueListenable<_i3.Box<dynamic>> get recordsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#recordsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#recordsListenable),
        ),
        returnValueForMissingStub: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#recordsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<dynamic>>);

  @override
  int get recordCount => (super.noSuchMethod(
        Invocation.getter(#recordCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i2.ValueListenable<_i3.Box<_i10.BatchTask>> get batchTasksListenable =>
      (super.noSuchMethod(
        Invocation.getter(#batchTasksListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<_i10.BatchTask>>(
          this,
          Invocation.getter(#batchTasksListenable),
        ),
        returnValueForMissingStub:
            _FakeValueListenable_0<_i3.Box<_i10.BatchTask>>(
          this,
          Invocation.getter(#batchTasksListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<_i10.BatchTask>>);

  @override
  bool get autoDeleteOriginal => (super.noSuchMethod(
        Invocation.getter(#autoDeleteOriginal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Box<dynamic> get searchIndexBox => (super.noSuchMethod(
        Invocation.getter(#searchIndexBox),
        returnValue: _FakeBox_1<dynamic>(
          this,
          Invocation.getter(#searchIndexBox),
        ),
        returnValueForMissingStub: _FakeBox_1<dynamic>(
          this,
          Invocation.getter(#searchIndexBox),
        ),
      ) as _i3.Box<dynamic>);

  @override
  _i2.ValueListenable<_i3.Box<_i11.FollowUpItem>> get followUpItemsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#followUpItemsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<_i11.FollowUpItem>>(
          this,
          Invocation.getter(#followUpItemsListenable),
        ),
        returnValueForMissingStub:
            _FakeValueListenable_0<_i3.Box<_i11.FollowUpItem>>(
          this,
          Invocation.getter(#followUpItemsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<_i11.FollowUpItem>>);

  @override
  _i3.Box<_i12.Citation> get citationsBox => (super.noSuchMethod(
        Invocation.getter(#citationsBox),
        returnValue: _FakeBox_1<_i12.Citation>(
          this,
          Invocation.getter(#citationsBox),
        ),
        returnValueForMissingStub: _FakeBox_1<_i12.Citation>(
          this,
          Invocation.getter(#citationsBox),
        ),
      ) as _i3.Box<_i12.Citation>);

  @override
  _i13.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveLocalAuditEntry(_i14.LocalAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocalAuditEntry,
          [entry],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i14.LocalAuditEntry> getAllLocalAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllLocalAuditEntries,
          [],
        ),
        returnValue: <_i14.LocalAuditEntry>[],
        returnValueForMissingStub: <_i14.LocalAuditEntry>[],
      ) as List<_i14.LocalAuditEntry>);

  @override
  _i13.Future<void> deleteLocalAuditEntries(List<dynamic>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocalAuditEntries,
          [keys],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveRecord(
    String? id,
    Map<String, dynamic>? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecord,
          [
            id,
            record,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  Map<String, dynamic>? getRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRecord,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as Map<String, dynamic>?);

  @override
  List<Map<String, dynamic>> getAllRecords() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecords,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> getRecordsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecordsByCategory,
          [category],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i13.Future<void> deleteRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i15.ConversationMemory? getConversationMemory(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationMemory,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      ) as _i15.ConversationMemory?);

  @override
  _i13.Future<void> saveConversationMemory(_i15.ConversationMemory? memory) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversationMemory,
          [memory],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteConversationMemory(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteConversationMemory,
          [conversationId],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i15.ConversationMemory> getAllConversationMemories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllConversationMemories,
          [],
        ),
        returnValue: <_i15.ConversationMemory>[],
        returnValueForMissingStub: <_i15.ConversationMemory>[],
      ) as List<_i15.ConversationMemory>);

  @override
  _i13.Future<void> saveBatchTask(_i10.BatchTask? task) => (super.noSuchMethod(
        Invocation.method(
          #saveBatchTask,
          [task],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i10.BatchTask> getAllBatchTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllBatchTasks,
          [],
        ),
        returnValue: <_i10.BatchTask>[],
        returnValueForMissingStub: <_i10.BatchTask>[],
      ) as List<_i10.BatchTask>);

  @override
  _i13.Future<void> deleteBatchTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatchTask,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> clearBatchTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearBatchTasks,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  T? getSetting<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i4.AppSettings getAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #getAppSettings,
          [],
        ),
        returnValue: _FakeAppSettings_2(
          this,
          Invocation.method(
            #getAppSettings,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAppSettings_2(
          this,
          Invocation.method(
            #getAppSettings,
            [],
          ),
        ),
      ) as _i4.AppSettings);

  @override
  _i13.Future<void> saveAppSettings(_i4.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAppSettings,
          [settings],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setAutoDeleteOriginal(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoDeleteOriginal,
          [value],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> savePaper(
    String? id,
    Map<String, dynamic>? paper,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePaper,
          [
            id,
            paper,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<Map<String, dynamic>> getSavedPapers() => (super.noSuchMethod(
        Invocation.method(
          #getSavedPapers,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i13.Future<void> deletePaper(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePaper,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveDocumentExtraction(
          _i16.DocumentExtraction? extraction) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocumentExtraction,
          [extraction],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i16.DocumentExtraction? getDocumentExtraction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentExtraction,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i16.DocumentExtraction?);

  @override
  List<_i16.DocumentExtraction> getAllDocumentExtractions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocumentExtractions,
          [],
        ),
        returnValue: <_i16.DocumentExtraction>[],
        returnValueForMissingStub: <_i16.DocumentExtraction>[],
      ) as List<_i16.DocumentExtraction>);

  @override
  _i16.DocumentExtraction? findDocumentExtractionByHash(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDocumentExtractionByHash,
          [hash],
        ),
        returnValueForMissingStub: null,
      ) as _i16.DocumentExtraction?);

  @override
  _i13.Future<void> deleteDocumentExtraction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentExtraction,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveDoctorConversation(
          _i17.DoctorConversation? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDoctorConversation,
          [conversation],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i17.DoctorConversation> getAllDoctorConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDoctorConversations,
          [],
        ),
        returnValue: <_i17.DoctorConversation>[],
        returnValueForMissingStub: <_i17.DoctorConversation>[],
      ) as List<_i17.DoctorConversation>);

  @override
  _i17.DoctorConversation? getDoctorConversation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoctorConversation,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i17.DoctorConversation?);

  @override
  _i13.Future<void> deleteDoctorConversation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDoctorConversation,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveFollowUpItem(_i11.FollowUpItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFollowUpItem,
          [item],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i11.FollowUpItem? getFollowUpItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFollowUpItem,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i11.FollowUpItem?);

  @override
  List<_i11.FollowUpItem> getAllFollowUpItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllFollowUpItems,
          [],
        ),
        returnValue: <_i11.FollowUpItem>[],
        returnValueForMissingStub: <_i11.FollowUpItem>[],
      ) as List<_i11.FollowUpItem>);

  @override
  List<_i11.FollowUpItem> getOverdueItems() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueItems,
          [],
        ),
        returnValue: <_i11.FollowUpItem>[],
        returnValueForMissingStub: <_i11.FollowUpItem>[],
      ) as List<_i11.FollowUpItem>);

  @override
  _i13.Future<void> deleteFollowUpItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFollowUpItem,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveRecordingAuditEntry(_i18.RecordingAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecordingAuditEntry,
          [entry],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i18.RecordingAuditEntry> getAllRecordingAuditEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRecordingAuditEntries,
          [],
        ),
        returnValue: <_i18.RecordingAuditEntry>[],
        returnValueForMissingStub: <_i18.RecordingAuditEntry>[],
      ) as List<_i18.RecordingAuditEntry>);

  @override
  _i13.Future<void> saveExportAuditEntry(_i19.ExportAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveExportAuditEntry,
          [entry],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i19.ExportAuditEntry> getAllExportAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllExportAuditEntries,
          [],
        ),
        returnValue: <_i19.ExportAuditEntry>[],
        returnValueForMissingStub: <_i19.ExportAuditEntry>[],
      ) as List<_i19.ExportAuditEntry>);

  @override
  _i13.Future<void> saveAuthAuditEntry(_i20.AuthAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAuthAuditEntry,
          [entry],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i20.AuthAuditEntry> getAllAuthAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllAuthAuditEntries,
          [],
        ),
        returnValue: <_i20.AuthAuditEntry>[],
        returnValueForMissingStub: <_i20.AuthAuditEntry>[],
      ) as List<_i20.AuthAuditEntry>);

  @override
  _i13.Future<void> saveIssueReport(_i21.IssueReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveIssueReport,
          [report],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i21.IssueReport> getAllIssueReports() => (super.noSuchMethod(
        Invocation.method(
          #getAllIssueReports,
          [],
        ),
        returnValue: <_i21.IssueReport>[],
        returnValueForMissingStub: <_i21.IssueReport>[],
      ) as List<_i21.IssueReport>);

  @override
  _i13.Future<void> deleteIssueReport(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIssueReport,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveConsentEntry(_i22.ConsentEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConsentEntry,
          [entry],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  List<_i22.ConsentEntry> getAllConsentEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllConsentEntries,
          [],
        ),
        returnValue: <_i22.ConsentEntry>[],
        returnValueForMissingStub: <_i22.ConsentEntry>[],
      ) as List<_i22.ConsentEntry>);

  @override
  _i22.ConsentEntry? getConsentEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getConsentEntry,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i22.ConsentEntry?);

  @override
  _i13.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [VaultService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultService extends _i1.Mock implements _i23.VaultService {
  @override
  _i13.Future<_i5.HealthRecord> saveDocumentToVault({
    required _i24.File? imageFile,
    required String? title,
    required String? category,
    String? notes,
    Map<String, dynamic>? additionalMetadata,
    void Function(String)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocumentToVault,
          [],
          {
            #imageFile: imageFile,
            #title: title,
            #category: category,
            #notes: notes,
            #additionalMetadata: additionalMetadata,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i13.Future<_i5.HealthRecord>.value(_FakeHealthRecord_3(
          this,
          Invocation.method(
            #saveDocumentToVault,
            [],
            {
              #imageFile: imageFile,
              #title: title,
              #category: category,
              #notes: notes,
              #additionalMetadata: additionalMetadata,
              #onProgress: onProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i5.HealthRecord>.value(_FakeHealthRecord_3(
          this,
          Invocation.method(
            #saveDocumentToVault,
            [],
            {
              #imageFile: imageFile,
              #title: title,
              #category: category,
              #notes: notes,
              #additionalMetadata: additionalMetadata,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i13.Future<_i5.HealthRecord>);

  @override
  _i13.Future<_i5.HealthRecord> saveDocumentWithAutoCategory({
    required _i24.File? imageFile,
    required String? title,
    String? notes,
    Map<String, dynamic>? additionalMetadata,
    void Function(String)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocumentWithAutoCategory,
          [],
          {
            #imageFile: imageFile,
            #title: title,
            #notes: notes,
            #additionalMetadata: additionalMetadata,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i13.Future<_i5.HealthRecord>.value(_FakeHealthRecord_3(
          this,
          Invocation.method(
            #saveDocumentWithAutoCategory,
            [],
            {
              #imageFile: imageFile,
              #title: title,
              #notes: notes,
              #additionalMetadata: additionalMetadata,
              #onProgress: onProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i5.HealthRecord>.value(_FakeHealthRecord_3(
          this,
          Invocation.method(
            #saveDocumentWithAutoCategory,
            [],
            {
              #imageFile: imageFile,
              #title: title,
              #notes: notes,
              #additionalMetadata: additionalMetadata,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i13.Future<_i5.HealthRecord>);

  @override
  _i13.Future<_i5.HealthRecord> saveConversationToVault(
    _i17.DoctorConversation? conversation, {
    void Function(String)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversationToVault,
          [conversation],
          {#onProgress: onProgress},
        ),
        returnValue: _i13.Future<_i5.HealthRecord>.value(_FakeHealthRecord_3(
          this,
          Invocation.method(
            #saveConversationToVault,
            [conversation],
            {#onProgress: onProgress},
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i5.HealthRecord>.value(_FakeHealthRecord_3(
          this,
          Invocation.method(
            #saveConversationToVault,
            [conversation],
            {#onProgress: onProgress},
          ),
        )),
      ) as _i13.Future<_i5.HealthRecord>);

  @override
  _i13.Future<({_i16.DocumentExtraction? extraction, _i5.HealthRecord record})>
      getCompleteDocument(String? healthRecordId) => (super.noSuchMethod(
            Invocation.method(
              #getCompleteDocument,
              [healthRecordId],
            ),
            returnValue: _i13.Future<
                ({
                  _i16.DocumentExtraction? extraction,
                  _i5.HealthRecord record
                })>.value((
              extraction: null,
              record: _FakeHealthRecord_3(
                this,
                Invocation.method(
                  #getCompleteDocument,
                  [healthRecordId],
                ),
              )
            )),
            returnValueForMissingStub: _i13.Future<
                ({
                  _i16.DocumentExtraction? extraction,
                  _i5.HealthRecord record
                })>.value((
              extraction: null,
              record: _FakeHealthRecord_3(
                this,
                Invocation.method(
                  #getCompleteDocument,
                  [healthRecordId],
                ),
              )
            )),
          ) as _i13.Future<
              ({
                _i16.DocumentExtraction? extraction,
                _i5.HealthRecord record
              })>);

  @override
  _i13.Future<
          List<
              ({_i16.DocumentExtraction? extraction, _i5.HealthRecord record})>>
      getAllDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getAllDocuments,
              [],
            ),
            returnValue: _i13.Future<
                List<
                    ({
                      _i16.DocumentExtraction? extraction,
                      _i5.HealthRecord record
                    })>>.value(<({
              _i16.DocumentExtraction? extraction,
              _i5.HealthRecord record
            })>[]),
            returnValueForMissingStub: _i13.Future<
                List<
                    ({
                      _i16.DocumentExtraction? extraction,
                      _i5.HealthRecord record
                    })>>.value(<({
              _i16.DocumentExtraction? extraction,
              _i5.HealthRecord record
            })>[]),
          ) as _i13.Future<
              List<
                  ({
                    _i16.DocumentExtraction? extraction,
                    _i5.HealthRecord record
                  })>>);

  @override
  _i13.Future<void> deleteDocument(String? healthRecordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [healthRecordId],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [StorageUsageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageUsageService extends _i1.Mock
    implements _i6.StorageUsageService {
  @override
  _i13.Future<_i6.StorageUsage> calculateStorageUsage() => (super.noSuchMethod(
        Invocation.method(
          #calculateStorageUsage,
          [],
        ),
        returnValue: _i13.Future<_i6.StorageUsage>.value(_FakeStorageUsage_4(
          this,
          Invocation.method(
            #calculateStorageUsage,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i6.StorageUsage>.value(_FakeStorageUsage_4(
          this,
          Invocation.method(
            #calculateStorageUsage,
            [],
          ),
        )),
      ) as _i13.Future<_i6.StorageUsage>);

  @override
  _i13.Future<bool> isStorageSufficient({int? requiredMB = 1024}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isStorageSufficient,
          [],
          {#requiredMB: requiredMB},
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  String formatBytes(int? bytes) => (super.noSuchMethod(
        Invocation.method(
          #formatBytes,
          [bytes],
        ),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.method(
            #formatBytes,
            [bytes],
          ),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.method(
            #formatBytes,
            [bytes],
          ),
        ),
      ) as String);
}

/// A class which mocks [DesktopNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDesktopNotificationService extends _i1.Mock
    implements _i26.DesktopNotificationService {
  @override
  set debugSettings(_i4.AppSettings? _debugSettings) => super.noSuchMethod(
        Invocation.setter(
          #debugSettings,
          _debugSettings,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.FlutterLocalNotificationsPlugin get notificationsPlugin =>
      (super.noSuchMethod(
        Invocation.getter(#notificationsPlugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_5(
          this,
          Invocation.getter(#notificationsPlugin),
        ),
        returnValueForMissingStub: _FakeFlutterLocalNotificationsPlugin_5(
          this,
          Invocation.getter(#notificationsPlugin),
        ),
      ) as _i7.FlutterLocalNotificationsPlugin);

  @override
  set notificationsPlugin(
          _i7.FlutterLocalNotificationsPlugin? _notificationsPlugin) =>
      super.noSuchMethod(
        Invocation.setter(
          #notificationsPlugin,
          _notificationsPlugin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isInitialized(bool? _isInitialized) => super.noSuchMethod(
        Invocation.setter(
          #isInitialized,
          _isInitialized,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void registerActionCallback(
    String? actionId,
    _i27.VoidCallback? callback,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #registerActionCallback,
          [
            actionId,
            callback,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<bool> isDoNotDisturbEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isDoNotDisturbEnabled,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> showDesktopNotification({
    required String? id,
    required String? title,
    required String? body,
    String? groupKey = r'general_alerts',
    List<_i26.NotificationAction>? actions,
    bool? sensitive = false,
    _i7.Importance? importance = _i7.Importance.max,
    _i7.Priority? priority = _i7.Priority.high,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDesktopNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #groupKey: groupKey,
            #actions: actions,
            #sensitive: sensitive,
            #importance: importance,
            #priority: priority,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> showStorageAlert({
    required String? title,
    required String? message,
    bool? isCritical = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showStorageAlert,
          [],
          {
            #title: title,
            #message: message,
            #isCritical: isCritical,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> showRecordingNotification({
    required String? title,
    required String? message,
    bool? sensitive = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showRecordingNotification,
          [],
          {
            #title: title,
            #message: message,
            #sensitive: sensitive,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> showModelStatus({
    required String? title,
    required String? message,
    bool? isError = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showModelStatus,
          [],
          {
            #title: title,
            #message: message,
            #isError: isError,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> scheduleReminder(_i11.FollowUpItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleReminder,
          [item],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> cancelReminder(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #cancelReminder,
          [itemId],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [MemoryMonitorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryMonitorService extends _i1.Mock
    implements _i8.MemoryMonitorService {
  @override
  _i13.Stream<_i8.MemoryStatus> get onStatusChanged => (super.noSuchMethod(
        Invocation.getter(#onStatusChanged),
        returnValue: _i13.Stream<_i8.MemoryStatus>.empty(),
        returnValueForMissingStub: _i13.Stream<_i8.MemoryStatus>.empty(),
      ) as _i13.Stream<_i8.MemoryStatus>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i8.MemoryStatus> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i13.Future<_i8.MemoryStatus>.value(_FakeMemoryStatus_6(
          this,
          Invocation.method(
            #refresh,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i8.MemoryStatus>.value(_FakeMemoryStatus_6(
          this,
          Invocation.method(
            #refresh,
            [],
          ),
        )),
      ) as _i13.Future<_i8.MemoryStatus>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  bool handleStartBackGesture(_i28.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i28.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> didPushRouteInformation(
          _i29.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i27.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAppLifecycleState(_i27.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i27.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i27.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i13.Future<_i27.AppExitResponse>.value(_i27.AppExitResponse.exit),
        returnValueForMissingStub:
            _i13.Future<_i27.AppExitResponse>.value(_i27.AppExitResponse.exit),
      ) as _i13.Future<_i27.AppExitResponse>);

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BatteryMonitorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatteryMonitorService extends _i1.Mock
    implements _i30.BatteryMonitorService {
  @override
  _i13.Future<int> get batteryLevel => (super.noSuchMethod(
        Invocation.getter(#batteryLevel),
        returnValue: _i13.Future<int>.value(0),
        returnValueForMissingStub: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);

  @override
  _i13.Future<_i31.BatteryState> get batteryState => (super.noSuchMethod(
        Invocation.getter(#batteryState),
        returnValue:
            _i13.Future<_i31.BatteryState>.value(_i31.BatteryState.full),
        returnValueForMissingStub:
            _i13.Future<_i31.BatteryState>.value(_i31.BatteryState.full),
      ) as _i13.Future<_i31.BatteryState>);

  @override
  _i13.Future<String?> checkPreRecordingBattery() => (super.noSuchMethod(
        Invocation.method(
          #checkPreRecordingBattery,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
        returnValueForMissingStub: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<bool> shouldOptimizeRecording() => (super.noSuchMethod(
        Invocation.method(
          #shouldOptimizeRecording,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  void startMonitoring({
    required dynamic Function(
      int,
      _i31.BatteryState,
    )? onUpdate,
    required _i27.VoidCallback? onCritical,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #startMonitoring,
          [],
          {
            #onUpdate: onUpdate,
            #onCritical: onCritical,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopMonitoring() => super.noSuchMethod(
        Invocation.method(
          #stopMonitoring,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox extends _i1.Mock implements _i3.Box<_i10.BatchTask> {
  @override
  Iterable<_i10.BatchTask> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <_i10.BatchTask>[],
        returnValueForMissingStub: <_i10.BatchTask>[],
      ) as Iterable<_i10.BatchTask>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Iterable<_i10.BatchTask> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <_i10.BatchTask>[],
        returnValueForMissingStub: <_i10.BatchTask>[],
      ) as Iterable<_i10.BatchTask>);

  @override
  _i10.BatchTask? getAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getAt,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i10.BatchTask?);

  @override
  Map<dynamic, _i10.BatchTask> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, _i10.BatchTask>{},
        returnValueForMissingStub: <dynamic, _i10.BatchTask>{},
      ) as Map<dynamic, _i10.BatchTask>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(
        Invocation.method(
          #keyAt,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Stream<_i3.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i13.Stream<_i3.BoxEvent>.empty(),
        returnValueForMissingStub: _i13.Stream<_i3.BoxEvent>.empty(),
      ) as _i13.Stream<_i3.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<void> put(
    dynamic key,
    _i10.BatchTask? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> putAt(
    int? index,
    _i10.BatchTask? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> putAll(Map<dynamic, _i10.BatchTask>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<int> add(_i10.BatchTask? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i13.Future<int>.value(0),
        returnValueForMissingStub: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);

  @override
  _i13.Future<Iterable<int>> addAll(Iterable<_i10.BatchTask>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i13.Future<Iterable<int>>.value(<int>[]),
        returnValueForMissingStub: _i13.Future<Iterable<int>>.value(<int>[]),
      ) as _i13.Future<Iterable<int>>);

  @override
  _i13.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i13.Future<int>.value(0),
        returnValueForMissingStub: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}
