// Mocks generated by Mockito 5.4.4 from annotations
// in sehatlocker/test/services/desktop_notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i6;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i8;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i10;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i12;
import 'package:flutter_local_notifications/src/types.dart' as _i13;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i9;
import 'package:hive_flutter/hive_flutter.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sehatlocker/models/app_settings.dart' as _i4;
import 'package:sehatlocker/models/auth_audit_entry.dart' as _i25;
import 'package:sehatlocker/models/batch_task.dart' as _i15;
import 'package:sehatlocker/models/citation.dart' as _i17;
import 'package:sehatlocker/models/consent_entry.dart' as _i27;
import 'package:sehatlocker/models/conversation_memory.dart' as _i20;
import 'package:sehatlocker/models/doctor_conversation.dart' as _i22;
import 'package:sehatlocker/models/document_extraction.dart' as _i21;
import 'package:sehatlocker/models/export_audit_entry.dart' as _i24;
import 'package:sehatlocker/models/follow_up_item.dart' as _i16;
import 'package:sehatlocker/models/health_pattern_insight.dart' as _i18;
import 'package:sehatlocker/models/issue_report.dart' as _i26;
import 'package:sehatlocker/models/local_audit_entry.dart' as _i19;
import 'package:sehatlocker/models/metric_snapshot.dart' as _i28;
import 'package:sehatlocker/models/recording_audit_entry.dart' as _i23;
import 'package:sehatlocker/models/user_profile.dart' as _i5;
import 'package:sehatlocker/services/local_storage_service.dart' as _i14;
import 'package:timezone/timezone.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSettings_2 extends _i1.SmartFake implements _i4.AppSettings {
  _FakeAppSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i5.UserProfile {
  _FakeUserProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i6.FlutterLocalNotificationsPlugin {
  @override
  _i7.Future<bool?> initialize(
    _i8.InitializationSettings? initializationSettings, {
    _i9.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i9.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i7.Future<bool?>.value(),
        returnValueForMissingStub: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);

  @override
  _i7.Future<_i9.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i7.Future<_i9.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i7.Future<_i9.NotificationAppLaunchDetails?>.value(),
          ) as _i7.Future<_i9.NotificationAppLaunchDetails?>);

  @override
  _i7.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i10.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i11.TZDateTime? scheduledDate,
    _i10.NotificationDetails? notificationDetails, {
    required _i12.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i13.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i9.RepeatInterval? repeatInterval,
    _i10.NotificationDetails? notificationDetails, {
    required _i12.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i10.NotificationDetails? notificationDetails, {
    _i12.AndroidScheduleMode? androidScheduleMode =
        _i12.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [
            id,
            title,
            body,
            repeatDurationInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue: _i7.Future<List<_i9.PendingNotificationRequest>>.value(
                <_i9.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i7.Future<List<_i9.PendingNotificationRequest>>.value(
                    <_i9.PendingNotificationRequest>[]),
          ) as _i7.Future<List<_i9.PendingNotificationRequest>>);

  @override
  _i7.Future<List<_i9.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i7.Future<List<_i9.ActiveNotification>>.value(
            <_i9.ActiveNotification>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i9.ActiveNotification>>.value(
                <_i9.ActiveNotification>[]),
      ) as _i7.Future<List<_i9.ActiveNotification>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i14.LocalStorageService {
  @override
  _i2.ValueListenable<_i3.Box<dynamic>> get recordsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#recordsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#recordsListenable),
        ),
        returnValueForMissingStub: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#recordsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<dynamic>>);

  @override
  int get recordCount => (super.noSuchMethod(
        Invocation.getter(#recordCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i2.ValueListenable<_i3.Box<_i15.BatchTask>> get batchTasksListenable =>
      (super.noSuchMethod(
        Invocation.getter(#batchTasksListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<_i15.BatchTask>>(
          this,
          Invocation.getter(#batchTasksListenable),
        ),
        returnValueForMissingStub:
            _FakeValueListenable_0<_i3.Box<_i15.BatchTask>>(
          this,
          Invocation.getter(#batchTasksListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<_i15.BatchTask>>);

  @override
  _i2.ValueListenable<_i3.Box<dynamic>> get settingsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#settingsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#settingsListenable),
        ),
        returnValueForMissingStub: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#settingsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<dynamic>>);

  @override
  bool get autoDeleteOriginal => (super.noSuchMethod(
        Invocation.getter(#autoDeleteOriginal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Box<dynamic> get searchIndexBox => (super.noSuchMethod(
        Invocation.getter(#searchIndexBox),
        returnValue: _FakeBox_1<dynamic>(
          this,
          Invocation.getter(#searchIndexBox),
        ),
        returnValueForMissingStub: _FakeBox_1<dynamic>(
          this,
          Invocation.getter(#searchIndexBox),
        ),
      ) as _i3.Box<dynamic>);

  @override
  _i2.ValueListenable<_i3.Box<_i16.FollowUpItem>> get followUpItemsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#followUpItemsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<_i16.FollowUpItem>>(
          this,
          Invocation.getter(#followUpItemsListenable),
        ),
        returnValueForMissingStub:
            _FakeValueListenable_0<_i3.Box<_i16.FollowUpItem>>(
          this,
          Invocation.getter(#followUpItemsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<_i16.FollowUpItem>>);

  @override
  _i3.Box<_i17.Citation> get citationsBox => (super.noSuchMethod(
        Invocation.getter(#citationsBox),
        returnValue: _FakeBox_1<_i17.Citation>(
          this,
          Invocation.getter(#citationsBox),
        ),
        returnValueForMissingStub: _FakeBox_1<_i17.Citation>(
          this,
          Invocation.getter(#citationsBox),
        ),
      ) as _i3.Box<_i17.Citation>);

  @override
  _i3.Box<_i18.HealthPatternInsight> get healthPatternInsightsBox =>
      (super.noSuchMethod(
        Invocation.getter(#healthPatternInsightsBox),
        returnValue: _FakeBox_1<_i18.HealthPatternInsight>(
          this,
          Invocation.getter(#healthPatternInsightsBox),
        ),
        returnValueForMissingStub: _FakeBox_1<_i18.HealthPatternInsight>(
          this,
          Invocation.getter(#healthPatternInsightsBox),
        ),
      ) as _i3.Box<_i18.HealthPatternInsight>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveLocalAuditEntry(_i19.LocalAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocalAuditEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i19.LocalAuditEntry> getAllLocalAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllLocalAuditEntries,
          [],
        ),
        returnValue: <_i19.LocalAuditEntry>[],
        returnValueForMissingStub: <_i19.LocalAuditEntry>[],
      ) as List<_i19.LocalAuditEntry>);

  @override
  _i7.Future<void> deleteLocalAuditEntries(List<dynamic>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocalAuditEntries,
          [keys],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveRecord(
    String? id,
    Map<String, dynamic>? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecord,
          [
            id,
            record,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, dynamic>? getRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRecord,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as Map<String, dynamic>?);

  @override
  List<Map<String, dynamic>> getAllRecords() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecords,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> getRecordsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecordsByCategory,
          [category],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i7.Future<void> deleteRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i20.ConversationMemory? getConversationMemory(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationMemory,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      ) as _i20.ConversationMemory?);

  @override
  _i7.Future<void> saveConversationMemory(_i20.ConversationMemory? memory) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversationMemory,
          [memory],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteConversationMemory(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteConversationMemory,
          [conversationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i20.ConversationMemory> getAllConversationMemories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllConversationMemories,
          [],
        ),
        returnValue: <_i20.ConversationMemory>[],
        returnValueForMissingStub: <_i20.ConversationMemory>[],
      ) as List<_i20.ConversationMemory>);

  @override
  _i7.Future<void> saveBatchTask(_i15.BatchTask? task) => (super.noSuchMethod(
        Invocation.method(
          #saveBatchTask,
          [task],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i15.BatchTask> getAllBatchTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllBatchTasks,
          [],
        ),
        returnValue: <_i15.BatchTask>[],
        returnValueForMissingStub: <_i15.BatchTask>[],
      ) as List<_i15.BatchTask>);

  @override
  _i7.Future<void> deleteBatchTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatchTask,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearBatchTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearBatchTasks,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  T? getSetting<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i4.AppSettings getAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #getAppSettings,
          [],
        ),
        returnValue: _FakeAppSettings_2(
          this,
          Invocation.method(
            #getAppSettings,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAppSettings_2(
          this,
          Invocation.method(
            #getAppSettings,
            [],
          ),
        ),
      ) as _i4.AppSettings);

  @override
  _i7.Future<void> saveAppSettings(_i4.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAppSettings,
          [settings],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i5.UserProfile getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        ),
      ) as _i5.UserProfile);

  @override
  _i7.Future<void> saveUserProfile(_i5.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setAutoDeleteOriginal(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoDeleteOriginal,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> savePaper(
    String? id,
    Map<String, dynamic>? paper,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePaper,
          [
            id,
            paper,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<Map<String, dynamic>> getSavedPapers() => (super.noSuchMethod(
        Invocation.method(
          #getSavedPapers,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i7.Future<void> deletePaper(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePaper,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveDocumentExtraction(
          _i21.DocumentExtraction? extraction) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocumentExtraction,
          [extraction],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i21.DocumentExtraction? getDocumentExtraction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentExtraction,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i21.DocumentExtraction?);

  @override
  List<_i21.DocumentExtraction> getAllDocumentExtractions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocumentExtractions,
          [],
        ),
        returnValue: <_i21.DocumentExtraction>[],
        returnValueForMissingStub: <_i21.DocumentExtraction>[],
      ) as List<_i21.DocumentExtraction>);

  @override
  _i21.DocumentExtraction? findDocumentExtractionByHash(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDocumentExtractionByHash,
          [hash],
        ),
        returnValueForMissingStub: null,
      ) as _i21.DocumentExtraction?);

  @override
  _i7.Future<void> deleteDocumentExtraction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentExtraction,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i21.DocumentExtraction> getDocumentsWithVerifiedExtractions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsWithVerifiedExtractions,
          [],
        ),
        returnValue: <_i21.DocumentExtraction>[],
        returnValueForMissingStub: <_i21.DocumentExtraction>[],
      ) as List<_i21.DocumentExtraction>);

  @override
  _i7.Future<void> saveDoctorConversation(
          _i22.DoctorConversation? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDoctorConversation,
          [conversation],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i22.DoctorConversation> getAllDoctorConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDoctorConversations,
          [],
        ),
        returnValue: <_i22.DoctorConversation>[],
        returnValueForMissingStub: <_i22.DoctorConversation>[],
      ) as List<_i22.DoctorConversation>);

  @override
  _i22.DoctorConversation? getDoctorConversation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoctorConversation,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i22.DoctorConversation?);

  @override
  _i7.Future<void> deleteDoctorConversation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDoctorConversation,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveFollowUpItem(_i16.FollowUpItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFollowUpItem,
          [item],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i16.FollowUpItem? getFollowUpItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFollowUpItem,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i16.FollowUpItem?);

  @override
  List<_i16.FollowUpItem> getAllFollowUpItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllFollowUpItems,
          [],
        ),
        returnValue: <_i16.FollowUpItem>[],
        returnValueForMissingStub: <_i16.FollowUpItem>[],
      ) as List<_i16.FollowUpItem>);

  @override
  List<_i16.FollowUpItem> getOverdueItems() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueItems,
          [],
        ),
        returnValue: <_i16.FollowUpItem>[],
        returnValueForMissingStub: <_i16.FollowUpItem>[],
      ) as List<_i16.FollowUpItem>);

  @override
  _i7.Future<void> deleteFollowUpItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFollowUpItem,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveHealthPatternInsight(
          _i18.HealthPatternInsight? insight) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHealthPatternInsight,
          [insight],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i18.HealthPatternInsight> getAllHealthPatternInsights() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHealthPatternInsights,
          [],
        ),
        returnValue: <_i18.HealthPatternInsight>[],
        returnValueForMissingStub: <_i18.HealthPatternInsight>[],
      ) as List<_i18.HealthPatternInsight>);

  @override
  _i7.Future<void> clearHealthPatternInsights() => (super.noSuchMethod(
        Invocation.method(
          #clearHealthPatternInsights,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveRecordingAuditEntry(_i23.RecordingAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecordingAuditEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i23.RecordingAuditEntry> getAllRecordingAuditEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRecordingAuditEntries,
          [],
        ),
        returnValue: <_i23.RecordingAuditEntry>[],
        returnValueForMissingStub: <_i23.RecordingAuditEntry>[],
      ) as List<_i23.RecordingAuditEntry>);

  @override
  _i7.Future<void> saveExportAuditEntry(_i24.ExportAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveExportAuditEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i24.ExportAuditEntry> getAllExportAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllExportAuditEntries,
          [],
        ),
        returnValue: <_i24.ExportAuditEntry>[],
        returnValueForMissingStub: <_i24.ExportAuditEntry>[],
      ) as List<_i24.ExportAuditEntry>);

  @override
  _i7.Future<void> saveAuthAuditEntry(_i25.AuthAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAuthAuditEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i25.AuthAuditEntry> getAllAuthAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllAuthAuditEntries,
          [],
        ),
        returnValue: <_i25.AuthAuditEntry>[],
        returnValueForMissingStub: <_i25.AuthAuditEntry>[],
      ) as List<_i25.AuthAuditEntry>);

  @override
  _i7.Future<void> saveIssueReport(_i26.IssueReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveIssueReport,
          [report],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i26.IssueReport> getAllIssueReports() => (super.noSuchMethod(
        Invocation.method(
          #getAllIssueReports,
          [],
        ),
        returnValue: <_i26.IssueReport>[],
        returnValueForMissingStub: <_i26.IssueReport>[],
      ) as List<_i26.IssueReport>);

  @override
  _i7.Future<void> deleteIssueReport(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIssueReport,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveConsentEntry(_i27.ConsentEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConsentEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i27.ConsentEntry> getAllConsentEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllConsentEntries,
          [],
        ),
        returnValue: <_i27.ConsentEntry>[],
        returnValueForMissingStub: <_i27.ConsentEntry>[],
      ) as List<_i27.ConsentEntry>);

  @override
  _i27.ConsentEntry? getConsentEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getConsentEntry,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i27.ConsentEntry?);

  @override
  _i7.Future<void> saveMetricSnapshot(_i28.MetricSnapshot? snapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMetricSnapshot,
          [snapshot],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i28.MetricSnapshot? getMetricSnapshot(String? metricName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMetricSnapshot,
          [metricName],
        ),
        returnValueForMissingStub: null,
      ) as _i28.MetricSnapshot?);

  @override
  List<_i28.MetricSnapshot> getAllMetricSnapshots() => (super.noSuchMethod(
        Invocation.method(
          #getAllMetricSnapshots,
          [],
        ),
        returnValue: <_i28.MetricSnapshot>[],
        returnValueForMissingStub: <_i28.MetricSnapshot>[],
      ) as List<_i28.MetricSnapshot>);

  @override
  _i7.Future<void> deleteMetricSnapshot(String? metricName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMetricSnapshot,
          [metricName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
