// Mocks generated by Mockito 5.4.4 from annotations
// in sehatlocker/test/services/llm_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i7;

import 'package:llama_cpp_dart/src/isolate_parent.dart' as _i4;
import 'package:llama_cpp_dart/src/isolate_scope.dart' as _i8;
import 'package:llama_cpp_dart/src/isolate_types.dart' as _i2;
import 'package:llama_cpp_dart/src/llama.dart' as _i5;
import 'package:llama_cpp_dart/src/llama_input.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sehatlocker/models/model_metadata.dart' as _i3;
import 'package:sehatlocker/models/model_option.dart' as _i11;
import 'package:sehatlocker/services/model_quantization_service.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLlamaLoad_0 extends _i1.SmartFake implements _i2.LlamaLoad {
  _FakeLlamaLoad_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModelMetadata_1 extends _i1.SmartFake implements _i3.ModelMetadata {
  _FakeModelMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LlamaParent].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlamaParent extends _i1.Mock implements _i4.LlamaParent {
  MockLlamaParent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  set messages(List<Map<String, dynamic>>? _messages) => super.noSuchMethod(
        Invocation.setter(
          #messages,
          _messages,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.LlamaLoad get loadCommand => (super.noSuchMethod(
        Invocation.getter(#loadCommand),
        returnValue: _FakeLlamaLoad_0(
          this,
          Invocation.getter(#loadCommand),
        ),
      ) as _i2.LlamaLoad);

  @override
  _i5.LlamaStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.LlamaStatus.uninitialized,
      ) as _i5.LlamaStatus);

  @override
  _i6.Stream<String> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  bool get isGenerating => (super.noSuchMethod(
        Invocation.getter(#isGenerating),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i4.CompletionEvent> get completions => (super.noSuchMethod(
        Invocation.getter(#completions),
        returnValue: _i6.Stream<_i4.CompletionEvent>.empty(),
      ) as _i6.Stream<_i4.CompletionEvent>);

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.Uint8List> saveState(_i8.LlamaScope? scope) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveState,
          [scope],
        ),
        returnValue: _i6.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i6.Future<_i7.Uint8List>);

  @override
  _i6.Future<void> loadState(
    _i8.LlamaScope? scope,
    _i7.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadState,
          [
            scope,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadSession(
    _i8.LlamaScope? scope,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSession,
          [
            scope,
            path,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> disposeScope(_i8.LlamaScope? scope) => (super.noSuchMethod(
        Invocation.method(
          #disposeScope,
          [scope],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> sendPrompt(
    String? prompt, {
    Object? scope,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPrompt,
          [prompt],
          {#scope: scope},
        ),
        returnValue: _i6.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #sendPrompt,
            [prompt],
            {#scope: scope},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> sendPromptWithImages(
    String? prompt,
    List<_i10.LlamaImage>? images, {
    Object? scope,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPromptWithImages,
          [
            prompt,
            images,
          ],
          {#scope: scope},
        ),
        returnValue: _i6.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #sendPromptWithImages,
            [
              prompt,
              images,
            ],
            {#scope: scope},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> waitForCompletion(String? promptId) => (super.noSuchMethod(
        Invocation.method(
          #waitForCompletion,
          [promptId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<double>> getEmbeddings(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #getEmbeddings,
          [prompt],
        ),
        returnValue: _i6.Future<List<double>>.value(<double>[]),
      ) as _i6.Future<List<double>>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelScope(
    Object? scope, {
    bool? cancelInFlight = true,
    bool? cancelQueued = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelScope,
          [scope],
          {
            #cancelInFlight: cancelInFlight,
            #cancelQueued: cancelQueued,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ModelOption].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelOption extends _i1.Mock implements _i11.ModelOption {
  MockModelOption() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  double get ramRequired => (super.noSuchMethod(
        Invocation.getter(#ramRequired),
        returnValue: 0.0,
      ) as double);

  @override
  double get storageRequired => (super.noSuchMethod(
        Invocation.getter(#storageRequired),
        returnValue: 0.0,
      ) as double);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  bool get isDesktopOnly => (super.noSuchMethod(
        Invocation.getter(#isDesktopOnly),
        returnValue: false,
      ) as bool);

  @override
  _i3.ModelMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeModelMetadata_1(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i3.ModelMetadata);

  @override
  String get license => (super.noSuchMethod(
        Invocation.getter(#license),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#license),
        ),
      ) as String);

  @override
  List<_i12.QuantizationFormat> get supportedQuantizations =>
      (super.noSuchMethod(
        Invocation.getter(#supportedQuantizations),
        returnValue: <_i12.QuantizationFormat>[],
      ) as List<_i12.QuantizationFormat>);
}
