// Mocks generated by Mockito 5.4.4 from annotations
// in sehatlocker/test/services/vault_service_categorization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:flutter/foundation.dart' as _i2;
import 'package:hive_flutter/hive_flutter.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sehatlocker/models/app_settings.dart' as _i4;
import 'package:sehatlocker/models/auth_audit_entry.dart' as _i18;
import 'package:sehatlocker/models/batch_task.dart' as _i7;
import 'package:sehatlocker/models/citation.dart' as _i9;
import 'package:sehatlocker/models/consent_entry.dart' as _i20;
import 'package:sehatlocker/models/conversation_memory.dart' as _i13;
import 'package:sehatlocker/models/doctor_conversation.dart' as _i15;
import 'package:sehatlocker/models/document_extraction.dart' as _i14;
import 'package:sehatlocker/models/export_audit_entry.dart' as _i17;
import 'package:sehatlocker/models/follow_up_item.dart' as _i8;
import 'package:sehatlocker/models/health_pattern_insight.dart' as _i10;
import 'package:sehatlocker/models/issue_report.dart' as _i19;
import 'package:sehatlocker/models/local_audit_entry.dart' as _i12;
import 'package:sehatlocker/models/recording_audit_entry.dart' as _i16;
import 'package:sehatlocker/models/user_profile.dart' as _i5;
import 'package:sehatlocker/services/local_storage_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSettings_2 extends _i1.SmartFake implements _i4.AppSettings {
  _FakeAppSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i5.UserProfile {
  _FakeUserProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i6.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueListenable<_i3.Box<dynamic>> get recordsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#recordsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#recordsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<dynamic>>);

  @override
  int get recordCount => (super.noSuchMethod(
        Invocation.getter(#recordCount),
        returnValue: 0,
      ) as int);

  @override
  _i2.ValueListenable<_i3.Box<_i7.BatchTask>> get batchTasksListenable =>
      (super.noSuchMethod(
        Invocation.getter(#batchTasksListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<_i7.BatchTask>>(
          this,
          Invocation.getter(#batchTasksListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<_i7.BatchTask>>);

  @override
  _i2.ValueListenable<_i3.Box<dynamic>> get settingsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#settingsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<dynamic>>(
          this,
          Invocation.getter(#settingsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<dynamic>>);

  @override
  bool get autoDeleteOriginal => (super.noSuchMethod(
        Invocation.getter(#autoDeleteOriginal),
        returnValue: false,
      ) as bool);

  @override
  _i3.Box<dynamic> get searchIndexBox => (super.noSuchMethod(
        Invocation.getter(#searchIndexBox),
        returnValue: _FakeBox_1<dynamic>(
          this,
          Invocation.getter(#searchIndexBox),
        ),
      ) as _i3.Box<dynamic>);

  @override
  _i2.ValueListenable<_i3.Box<_i8.FollowUpItem>> get followUpItemsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#followUpItemsListenable),
        returnValue: _FakeValueListenable_0<_i3.Box<_i8.FollowUpItem>>(
          this,
          Invocation.getter(#followUpItemsListenable),
        ),
      ) as _i2.ValueListenable<_i3.Box<_i8.FollowUpItem>>);

  @override
  _i3.Box<_i9.Citation> get citationsBox => (super.noSuchMethod(
        Invocation.getter(#citationsBox),
        returnValue: _FakeBox_1<_i9.Citation>(
          this,
          Invocation.getter(#citationsBox),
        ),
      ) as _i3.Box<_i9.Citation>);

  @override
  _i3.Box<_i10.HealthPatternInsight> get healthPatternInsightsBox =>
      (super.noSuchMethod(
        Invocation.getter(#healthPatternInsightsBox),
        returnValue: _FakeBox_1<_i10.HealthPatternInsight>(
          this,
          Invocation.getter(#healthPatternInsightsBox),
        ),
      ) as _i3.Box<_i10.HealthPatternInsight>);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveLocalAuditEntry(_i12.LocalAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocalAuditEntry,
          [entry],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i12.LocalAuditEntry> getAllLocalAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllLocalAuditEntries,
          [],
        ),
        returnValue: <_i12.LocalAuditEntry>[],
      ) as List<_i12.LocalAuditEntry>);

  @override
  _i11.Future<void> deleteLocalAuditEntries(List<dynamic>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocalAuditEntries,
          [keys],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveRecord(
    String? id,
    Map<String, dynamic>? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecord,
          [
            id,
            record,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  Map<String, dynamic>? getRecord(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getRecord,
        [id],
      )) as Map<String, dynamic>?);

  @override
  List<Map<String, dynamic>> getAllRecords() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecords,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> getRecordsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecordsByCategory,
          [category],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i11.Future<void> deleteRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i13.ConversationMemory? getConversationMemory(String? conversationId) =>
      (super.noSuchMethod(Invocation.method(
        #getConversationMemory,
        [conversationId],
      )) as _i13.ConversationMemory?);

  @override
  _i11.Future<void> saveConversationMemory(_i13.ConversationMemory? memory) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversationMemory,
          [memory],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteConversationMemory(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteConversationMemory,
          [conversationId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i13.ConversationMemory> getAllConversationMemories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllConversationMemories,
          [],
        ),
        returnValue: <_i13.ConversationMemory>[],
      ) as List<_i13.ConversationMemory>);

  @override
  _i11.Future<void> saveBatchTask(_i7.BatchTask? task) => (super.noSuchMethod(
        Invocation.method(
          #saveBatchTask,
          [task],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i7.BatchTask> getAllBatchTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllBatchTasks,
          [],
        ),
        returnValue: <_i7.BatchTask>[],
      ) as List<_i7.BatchTask>);

  @override
  _i11.Future<void> deleteBatchTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatchTask,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> clearBatchTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearBatchTasks,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  T? getSetting<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getSetting,
        [key],
        {#defaultValue: defaultValue},
      )) as T?);

  @override
  _i4.AppSettings getAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #getAppSettings,
          [],
        ),
        returnValue: _FakeAppSettings_2(
          this,
          Invocation.method(
            #getAppSettings,
            [],
          ),
        ),
      ) as _i4.AppSettings);

  @override
  _i11.Future<void> saveAppSettings(_i4.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAppSettings,
          [settings],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i5.UserProfile getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        ),
      ) as _i5.UserProfile);

  @override
  _i11.Future<void> saveUserProfile(_i5.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setAutoDeleteOriginal(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoDeleteOriginal,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> savePaper(
    String? id,
    Map<String, dynamic>? paper,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePaper,
          [
            id,
            paper,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<Map<String, dynamic>> getSavedPapers() => (super.noSuchMethod(
        Invocation.method(
          #getSavedPapers,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i11.Future<void> deletePaper(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePaper,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveDocumentExtraction(
          _i14.DocumentExtraction? extraction) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocumentExtraction,
          [extraction],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i14.DocumentExtraction? getDocumentExtraction(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getDocumentExtraction,
        [id],
      )) as _i14.DocumentExtraction?);

  @override
  List<_i14.DocumentExtraction> getAllDocumentExtractions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocumentExtractions,
          [],
        ),
        returnValue: <_i14.DocumentExtraction>[],
      ) as List<_i14.DocumentExtraction>);

  @override
  _i14.DocumentExtraction? findDocumentExtractionByHash(String? hash) =>
      (super.noSuchMethod(Invocation.method(
        #findDocumentExtractionByHash,
        [hash],
      )) as _i14.DocumentExtraction?);

  @override
  _i11.Future<void> deleteDocumentExtraction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentExtraction,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveDoctorConversation(
          _i15.DoctorConversation? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDoctorConversation,
          [conversation],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i15.DoctorConversation> getAllDoctorConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDoctorConversations,
          [],
        ),
        returnValue: <_i15.DoctorConversation>[],
      ) as List<_i15.DoctorConversation>);

  @override
  _i15.DoctorConversation? getDoctorConversation(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getDoctorConversation,
        [id],
      )) as _i15.DoctorConversation?);

  @override
  _i11.Future<void> deleteDoctorConversation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDoctorConversation,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveFollowUpItem(_i8.FollowUpItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFollowUpItem,
          [item],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i8.FollowUpItem? getFollowUpItem(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getFollowUpItem,
        [id],
      )) as _i8.FollowUpItem?);

  @override
  List<_i8.FollowUpItem> getAllFollowUpItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllFollowUpItems,
          [],
        ),
        returnValue: <_i8.FollowUpItem>[],
      ) as List<_i8.FollowUpItem>);

  @override
  List<_i8.FollowUpItem> getOverdueItems() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueItems,
          [],
        ),
        returnValue: <_i8.FollowUpItem>[],
      ) as List<_i8.FollowUpItem>);

  @override
  _i11.Future<void> deleteFollowUpItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFollowUpItem,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveHealthPatternInsight(
          _i10.HealthPatternInsight? insight) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHealthPatternInsight,
          [insight],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i10.HealthPatternInsight> getAllHealthPatternInsights() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHealthPatternInsights,
          [],
        ),
        returnValue: <_i10.HealthPatternInsight>[],
      ) as List<_i10.HealthPatternInsight>);

  @override
  _i11.Future<void> clearHealthPatternInsights() => (super.noSuchMethod(
        Invocation.method(
          #clearHealthPatternInsights,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveRecordingAuditEntry(_i16.RecordingAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecordingAuditEntry,
          [entry],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i16.RecordingAuditEntry> getAllRecordingAuditEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRecordingAuditEntries,
          [],
        ),
        returnValue: <_i16.RecordingAuditEntry>[],
      ) as List<_i16.RecordingAuditEntry>);

  @override
  _i11.Future<void> saveExportAuditEntry(_i17.ExportAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveExportAuditEntry,
          [entry],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i17.ExportAuditEntry> getAllExportAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllExportAuditEntries,
          [],
        ),
        returnValue: <_i17.ExportAuditEntry>[],
      ) as List<_i17.ExportAuditEntry>);

  @override
  _i11.Future<void> saveAuthAuditEntry(_i18.AuthAuditEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAuthAuditEntry,
          [entry],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i18.AuthAuditEntry> getAllAuthAuditEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllAuthAuditEntries,
          [],
        ),
        returnValue: <_i18.AuthAuditEntry>[],
      ) as List<_i18.AuthAuditEntry>);

  @override
  _i11.Future<void> saveIssueReport(_i19.IssueReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveIssueReport,
          [report],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i19.IssueReport> getAllIssueReports() => (super.noSuchMethod(
        Invocation.method(
          #getAllIssueReports,
          [],
        ),
        returnValue: <_i19.IssueReport>[],
      ) as List<_i19.IssueReport>);

  @override
  _i11.Future<void> deleteIssueReport(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIssueReport,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveConsentEntry(_i20.ConsentEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConsentEntry,
          [entry],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i20.ConsentEntry> getAllConsentEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllConsentEntries,
          [],
        ),
        returnValue: <_i20.ConsentEntry>[],
      ) as List<_i20.ConsentEntry>);

  @override
  _i20.ConsentEntry? getConsentEntry(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getConsentEntry,
        [id],
      )) as _i20.ConsentEntry?);

  @override
  _i11.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
