// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/search_entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3341964361250653690),
      name: 'SearchEntry',
      lastPropertyId: const obx_int.IdUid(8, 6520098932234305097),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4862383537078515450),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4610292965125499987),
            name: 'sourceId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 826312180012880664)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 212158970008794442),
            name: 'type',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 3494041055772686156)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8606824330787196695),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4458958916607200666),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3818969871090289759),
            name: 'subtitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4479012750261995974),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6520098932234305097),
            name: 'keywords',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 3341964361250653690),
      lastIndexId: const obx_int.IdUid(2, 3494041055772686156),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SearchEntry: obx_int.EntityDefinition<SearchEntry>(
        model: _entities[0],
        toOneRelations: (SearchEntry object) => [],
        toManyRelations: (SearchEntry object) => {},
        getId: (SearchEntry object) => object.id,
        setId: (SearchEntry object, int id) {
          object.id = id;
        },
        objectToFB: (SearchEntry object, fb.Builder fbb) {
          final sourceIdOffset = fbb.writeString(object.sourceId);
          final typeOffset = fbb.writeString(object.type);
          final contentOffset = fbb.writeString(object.content);
          final titleOffset = fbb.writeString(object.title);
          final subtitleOffset = fbb.writeString(object.subtitle);
          final keywordsOffset = fbb.writeString(object.keywords);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, sourceIdOffset);
          fbb.addOffset(2, typeOffset);
          fbb.addOffset(3, contentOffset);
          fbb.addOffset(4, titleOffset);
          fbb.addOffset(5, subtitleOffset);
          fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
          fbb.addOffset(7, keywordsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final sourceIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final subtitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final timestampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final keywordsParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final object = SearchEntry(
              sourceId: sourceIdParam,
              type: typeParam,
              content: contentParam,
              title: titleParam,
              subtitle: subtitleParam,
              timestamp: timestampParam,
              keywords: keywordsParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SearchEntry] entity fields to define ObjectBox queries.
class SearchEntry_ {
  /// see [SearchEntry.id]
  static final id =
      obx.QueryIntegerProperty<SearchEntry>(_entities[0].properties[0]);

  /// see [SearchEntry.sourceId]
  static final sourceId =
      obx.QueryStringProperty<SearchEntry>(_entities[0].properties[1]);

  /// see [SearchEntry.type]
  static final type =
      obx.QueryStringProperty<SearchEntry>(_entities[0].properties[2]);

  /// see [SearchEntry.content]
  static final content =
      obx.QueryStringProperty<SearchEntry>(_entities[0].properties[3]);

  /// see [SearchEntry.title]
  static final title =
      obx.QueryStringProperty<SearchEntry>(_entities[0].properties[4]);

  /// see [SearchEntry.subtitle]
  static final subtitle =
      obx.QueryStringProperty<SearchEntry>(_entities[0].properties[5]);

  /// see [SearchEntry.timestamp]
  static final timestamp =
      obx.QueryDateProperty<SearchEntry>(_entities[0].properties[6]);

  /// see [SearchEntry.keywords]
  static final keywords =
      obx.QueryStringProperty<SearchEntry>(_entities[0].properties[7]);
}
